// Generated by Wrangler by running `wrangler types`

interface Env {
	TWITTER_CLIENT_ID: string;
	TWITTER_CLIENT_SECRET: string;
	BOT_SCHEDULER: DurableObjectNamespace<import("./src/index").BotScheduler>;
	DB: D1Database;
}
